modules:
  - name: core
    payload: "src@abc123"
    seconds: 0.1
  - name: utils
    payload: "src@def456"
    seconds: 0.1

tests:
  # Passing: expected digest matches module "core"
  - name: unit-core
    module: core
    seconds: 0.05
    expected_digest: "4fc41e5669eafc53d839cd3f1f8c5fa4b5406f85ea35f94da8a4d9151e7523de"

  # Failing: intentionally wrong expected digest for demonstration
  - name: unit-utils
    module: utils
    seconds: 0.05
    expected_digest: "WRONG_DIGEST"
