name: CI

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements-dev.txt

      - name: Lint (ruff)
        run: python -m ruff check . --output-format=github || true

      - name: Format (black)
        run: python -m black --check .

      - name: Type check (mypy)
        run: python -m mypy sim

      - name: Tests
        run: pytest
